language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt -r requirements-test.txt
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y --force-yes
before_script:
  - rethinkdb --daemon
script:
  - sleep 4
  - nosetests --with-coverage
after_success: coveralls