language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: nosetests
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb -y
  - rethinkdb