language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y --force-yes
before_script: rethinkdb --daemon
script: nosetests